import os
import re
import math
import io
import zipfile

import pandas as pd
import requests


class CricsheetProcessor:
    """Handles downloading and processing of Cricsheet T20 data (JSON format)."""

    def __init__(self, zip_path='Research/t20s_male_json.zip', extract_path='Research'):
        self.url = 'https://cricsheet.org/downloads/t20s_male_json.zip'
        self.zip_path = zip_path
        self.extract_path = extract_path
        self.readme_path = os.path.join(extract_path, 'README.txt')

    def download_and_extract(self):
        """Downloads the JSON zip from Cricsheet and extracts it, if not already present."""
        if os.path.exists(self.readme_path):
            print(f"Data already extracted at '{self.extract_path}'. Skipping download.")
            return

        if os.path.exists(self.zip_path):
            print(f"Zip found at '{self.zip_path}'. Extracting...")
            with zipfile.ZipFile(self.zip_path, 'r') as z:
                z.extractall(self.extract_path)
            print(f"Extracted to '{self.extract_path}'.")
        else:
            print(f"Downloading data from {self.url}...")
            r = requests.get(self.url, stream=True)
            r.raise_for_status()
            with zipfile.ZipFile(io.BytesIO(r.content)) as z:
                z.extractall(self.extract_path)
            print(f"Downloaded and extracted to '{self.extract_path}'.")

    def process_metadata(self):
        """
        Parses Research/README.txt and returns a cleaned DataFrame of match metadata.

        The README.txt format (6 columns, ' - ' separated):
            YYYY-MM-DD - <team_type> - <match_type> - <gender> - <match_id> - <teams>

        Example:
            2007-09-13 - international - T20 - male - 287857 - Bangladesh vs West Indies
        """
        if not os.path.exists(self.readme_path):
            raise FileNotFoundError(
                f"README.txt not found at '{self.readme_path}'. "
                "Run download_and_extract() first."
            )

        date_pattern = re.compile(r'^\d{4}-\d{2}-\d{2}')
        records = []

        with open(self.readme_path, 'r', encoding='utf-8', errors='replace') as f:
            for line in f:
                line = line.strip()
                if date_pattern.match(line):
                    parts = [p.strip() for p in line.split(' - ')]
                    if len(parts) >= 6:
                        records.append({
                            'date':       parts[0],
                            'team_type':  parts[1],
                            'match_type': parts[2],
                            'gender':     parts[3],
                            'match_id':   parts[4],
                            'teams':      parts[5],
                        })

        if not records:
            raise ValueError("No match records parsed from README.txt. Check the file format.")

        df = pd.DataFrame(records)
        df['match_id'] = df['match_id'].astype(str)
        df['date'] = pd.to_datetime(df['date'], errors='coerce')

        # Aliases for downstream compatibility with the notebook
        df['Cricsheet_id']   = df['match_id']
        df['Cricsheet_name'] = df['teams']

        return df.reset_index(drop=True)


class MatchDataProcessor:
    """Handles ball-by-ball match data processing from the consolidated CSV."""

    def __init__(self, data_path='data/consolidated_t20_data.csv'):
        self.data_path = data_path
        self._consolidated_df = None

    def _load_consolidated(self):
        """Loads the pre-merged consolidated ball-by-ball CSV once (lazy)."""
        if self._consolidated_df is None:
            if not os.path.exists(self.data_path):
                raise FileNotFoundError(
                    f"Consolidated data not found at '{self.data_path}'. "
                    "Please ensure the file exists (generated by Data_preprocessing.ipynb)."
                )
            print(f"Loading consolidated data from '{self.data_path}'...")
            self._consolidated_df = pd.read_csv(self.data_path, low_memory=False)
            print(f"  Loaded {len(self._consolidated_df):,} rows.")
        return self._consolidated_df

    def load_ball_by_ball(self, match_ids, team_name):
        """
        Filters the consolidated CSV to rows where batting_team == team_name
        and the match ID is in match_ids. Adds row_index and over_number columns.
        """
        raw = self._load_consolidated()

        # Normalise match_ids: strings only, drop NaN
        valid_ids = {str(mid).strip() for mid in match_ids if pd.notna(mid)}

        id_col = 'match_id' if 'match_id' in raw.columns else None
        if id_col:
            mask = (
                raw['batting_team'].eq(team_name) &
                raw[id_col].astype(str).isin(valid_ids)
            )
        else:
            # Fallback: filter only by team
            mask = raw['batting_team'].eq(team_name)

        df = raw[mask].copy().reset_index(drop=True)

        if df.empty:
            print(f"No ball-by-ball data found for team '{team_name}'.")
            return pd.DataFrame()

        df['row_index']   = df.index
        df['ball']        = df['ball'].astype(float)
        df['over_number'] = df['ball'].apply(lambda x: int(math.ceil(x)))

        # Drop extras / wicket detail columns where present
        cols_to_drop = [
            'wides', 'noballs', 'byes', 'legbyes', 'penalty',
            'wicket_type', 'player_dismissed',
            'other_wicket_type', 'other_player_dismissed',
        ]
        df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

        return df

    def group_by_death_overs(self, df, batting_team, start_over=17, end_over=20):
        """Groups data by date and bowling team for the specified over range."""
        if df.empty:
            return pd.DataFrame()

        filtered = df[
            df['batting_team'].eq(batting_team) &
            df['over_number'].ge(start_over) &
            df['over_number'].le(end_over)
        ]

        if filtered.empty:
            return pd.DataFrame()

        # Use 'start_date' if present (CSV export), else fall back to 'date'
        date_col = 'start_date' if 'start_date' in filtered.columns else 'date'

        grouped = (
            filtered
            .groupby([date_col, 'bowling_team'])
            .agg(total_runs=('runs_off_bat', 'sum'), total_balls=('ball', 'count'))
            .reset_index()
        )
        grouped['strike_rate'] = (grouped['total_runs'] / grouped['total_balls']) * 100

        return grouped
